<?php
/**
 * Created by JetBrains PhpStorm.
 * User: user
 * Date: 31.07.13
 * Time: 23:16
 * To change this template use File | Settings | File Templates.
 */

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();